---

- name: Include windows-osquery
  ansible.builtin.include_tasks: windows-osquery.yml

- name: Include testing
  ansible.builtin.include_tasks: testing.yml
  when: osquery_testing|bool

- name: Include profiling
  ansible.builtin.include_tasks: profiling.yml
  when: osquery_profiling|bool
