---

## https://osquery.io/downloads/
## https://www.facebook.com/notes/protect-the-graph/introducing-osquery-for-windows/1775110322729111/

## FIXME! "ERROR: Exception calling "RemovableAccessRule" with "1" argument(s): "Some or all identity references could not be translated."
##      https://github.com/facebook/osquery/blob/e8045f1dd33ee4ed3a424ba70e71c1ff07b2a6e9/tools/provision/chocolatey/osquery_utils.ps1#L36
##      https://msdn.microsoft.com/en-us/library/windows/desktop/aa379649(v=vs.85).aspx
- name: Install osquery package with chocolatey
  win_chocolatey:
    name: osquery
## ansible 2.1+. better after configuration
#    install_args: "/InstallService"
#  ignore_errors: true
  when: win_osquery_url == ''

- name: Install osquery from url
  win_package:
    path: "{{ win_osquery_url }}"
    product_id: '{A00B7823-A9A3-4577-A804-A07C43765AFD}'
    state: present
  when: win_osquery_url != ''

- name: update osquery windows packs
  win_template:
    src: "{{ item }}.conf.j2"
    dest: "c:\\ProgramData\\osquery\\packs\\{{ item }}.conf"
    backup: yes
  with_items: "{{ win_osquery_upload_packs }}"
  register: conf1

- name: Configure osqueryd
  win_template:
    src: "{{ win_osquery_template }}"
#    dest: "%ProgramData%\\osquery\\osquery.conf"
    dest: "c:\\ProgramData\\osquery\\osquery.conf"
  register: conf2

- name: Configure osqueryd flags
  win_template:
    src: "{{ win_osquery_flags_template }}"
    dest: "c:\\ProgramData\\osquery\\osquery.flags"
  register: conf3

- name: update osqueryd.exe path
  win_template:
    src: manage-osqueryd.ps1.j2
    dest: "c:\\ProgramData\\osquery\\manage-osqueryd.ps1"
    backup: yes

- name: Restrict permissions for Users on osquery directories
  win_acl:
    path: "{{ item.p }}"
    user: "{{ item.u }}"
    rights: "{{ item.r }}"
    type: "{{ item.t }}"
    state: "{{ item.s }}"
    inherit: 'None'
    propagation: 'InheritOnly'
  with_items:
    - { p: 'C:\ProgramData\osquery', u: 'BUILTIN\Users', r: write, t: allow, s: absent }
    - { p: 'C:\ProgramData\osquery\certs', u: 'BUILTIN\Users', r: write, t: allow, s: absent }
    - { p: 'C:\ProgramData\osquery\log', u: 'BUILTIN\Users', r: 'read,write', t: allow, s: absent }
    - { p: 'C:\ProgramData\osquery\packs', u: 'BUILTIN\Users', r: write, t: allow, s: absent }

# https://github.com/facebook/osquery/pull/3887
# https://osquery.readthedocs.io/en/stable/installation/install-windows/#enabling-windows-event-log-support
- name: Check if osquery windows event log installed
  win_stat:
    path: c:\ProgramData\osquery\osquery_man_installed
  register: osquerymaninstalled
- block:
    - name: fixme! missing file in msi
      win_copy:
        src: osquery.man
        dest: C:\ProgramData\osquery\osquery.man
      when: win_osquery_url != ''

    - name: Enable Windows Event Log support
      win_command: wevtutil im C:\ProgramData\osquery\osquery.man

#    - name: Check WINEVT osquery channel configuration
#      win_command: "wevtutil gl \"osquery\""
#      changed_when: false
#      register: evtosquery

# FIXME! not working
    - name: WINEVT osquery Channel Event Log size review
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\osquery"
        value: MaxSize
        datatype: dword
        data: "{{ win_eventlog_maxsize }}"
#      when: "'maxsize: {{ win_eventlog_maxsize }}' not in evtosquery.stdout"

    - name: WINEVT Channels Event Log retention review
      win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\osquery"
        value: Retention
        datatype: dword
        data: "{{ win_eventlog_retention }}"
#      when: "'retention: false' not in evtosquery.stdout"

#    - name: Check WINEVT osquery channel configuration
#      win_command: "wevtutil gl \"osquery\""
#      changed_when: false

#    - name: WINEVT osquery channel configuration - wevtutil
#      win_command: "wevtutil sl \"osquery\" /ms:{{ win_eventlog_maxsize }} /rt:false /ab:false"
#      when: "'maxsize: {{ win_eventlog_maxsize }}' not in evtosquery.stdout"

#    - name: Check WINEVT osquery channel configuration
#      win_command: "wevtutil gl \"osquery\""
#      changed_when: false

    - name: Add task marker
      win_file:
        path: c:\ProgramData\osquery\osquery_man_installed
        state: touch
  when: win_osquery_enable_winevtx_logging and not osquerymaninstalled.stat.exists
- name: Check if osquery windows event log status disabled
  win_stat:
    path: c:\ProgramData\osquery\osquery_man_uninstalled
  register: osquerymanimported
- block:
    - name: Disable Windows Event Log support
      win_command: wevtutil um C:\ProgramData\osquery\osquery.man
    - name: Add task marker
      win_file:
        path: c:\ProgramData\osquery\osquery_man_uninstalled
        state: touch
  when: not win_osquery_enable_winevtx_logging and not osquerymanimported.stat.exists

- block:
# https://github.com/ansible/ansible/issues/35661
    - name: validate osqueryd config
      win_command: "c:\\ProgramData\\osquery\\osqueryi.exe --config_path c:\\ProgramData\\osquery\\osquery.conf --config_check --verbose"
    - name: Install and start osqueryd service
#      win_shell: "%ProgramData%\\osquery\\manage-osqueryd.ps1 -install -start"
      win_shell: "{{ item }}"
      with_items:
#        - "PowerShell.exe -ExecutionPolicy Bypass -File c:\\ProgramData\\osquery\\manage-osqueryd.ps1 -install"
        - "PowerShell.exe -ExecutionPolicy Bypass -File c:\\ProgramData\\osquery\\manage-osqueryd.ps1 -install -args '--flagfile \\ProgramData\\osquery\\osquery.flags'"
        - "PowerShell.exe -ExecutionPolicy Bypass -File c:\\ProgramData\\osquery\\manage-osqueryd.ps1 -start"
      ignore_errors: true
  when: win_osqueryd_service_enable and (conf1.changed or conf2.changed or conf3.changed)
- block:
    - name: Uninstall and stop osqueryd service
      win_shell: "{{ item }}"
      with_items:
        - "PowerShell.exe -ExecutionPolicy Bypass -File c:\\ProgramData\\osquery\\manage-osqueryd.ps1 -uninstall"
        - "PowerShell.exe -ExecutionPolicy Bypass -File c:\\ProgramData\\osquery\\manage-osqueryd.ps1 -stop"
      ignore_errors: true
  when: not win_osqueryd_service_enable

- name: Check osquery winevt log
  win_shell: Get-WinEvent -LogName 'Facebook-osquery'
  register: winevtosquery
  ignore_errors: true
  changed_when: false
- debug: var=winevtosquery.stdout_lines
