---

## https://osquery.io/downloads/
## https://www.facebook.com/notes/protect-the-graph/introducing-osquery-for-windows/1775110322729111/

## FIXME! "ERROR: Exception calling "RemovableAccessRule" with "1" argument(s):
##      "Some or all identity references could not be translated."
## https://github.com/facebook/osquery/blob/e8045f1dd33ee4ed3a424ba70e71c1ff07b2a6e9/tools/provision/\
#       chocolatey/osquery_utils.ps1#L36
## https://msdn.microsoft.com/en-us/library/windows/desktop/aa379649(v=vs.85).aspx
- name: Install osquery package with chocolatey
  chocolatey.chocolatey.win_chocolatey:
    name: osquery
  ## ansible 2.1+. better after configuration
  #   install_args: "/InstallService"
  when: not win_osquery_url|string

- name: Install osquery from url
  ansible.windows.win_package:
    path: "{{ win_osquery_url }}"
    product_id: '{A00B7823-A9A3-4577-A804-A07C43765AFD}'
    state: present
  when: win_osquery_url|string
  register: pkg_result
  until: pkg_result is success

- name: Include osquery fim pack
  ansible.builtin.set_fact:
    win_osquery_upload_packs: "{{ win_osquery_upload_packs + ['osquery-fim-pack'] }}"
    win_osquery_packs: "{{ win_osquery_packs + ['osquery-fim-pack'] }}"
  when: win_osquery_fim

- name: Ensure packs directory exists
  ansible.windows.win_file:
    dest: "{{ win_osquery_dir }}\\packs"
    state: directory

- name: Update osquery windows packs
  ansible.windows.win_template:
    src: "{{ item }}.conf.j2"
    dest: "{{ win_osquery_dir }}\\packs\\{{ item }}.conf"
    backup: yes
  with_items: "{{ win_osquery_upload_packs }}"
  register: conf1
  notify:
    - Restart osqueryd
    - Restart osqueryd - script

- name: Import palantir
  ansible.builtin.import_tasks: palantir.yml
  when: win_osquery_palantir|bool

- name: Osquery secret file
  when: win_osquery_secret is defined and win_osquery_secret and win_osquery_secret_path is defined and win_osquery_secret_path|string
  block:
    - name: Check if have osquery secret file
      ansible.windows.win_stat:
        path: "{{ win_osquery_secret_path }}"
      register: secretf
    - name: Ensure secret directory exists
      ansible.windows.win_file:
        dest: "{{ win_osquery_secret_path | win_dirname }}"
        state: directory
    - name: Create osquery secret file
      community.windows.win_lineinfile:
        path: "{{ win_osquery_secret_path }}"
        regex: '^.*'
        line: "{{ win_osquery_secret }}"
        state: present
        create: yes
      when: (not secretf.stat.exists or secretf.stat.size == 0) and win_osquery_secret
    - name: Restrict permissions for Users on osquery secret
      ansible.windows.win_acl:
        path: "{{ item.p }}"
        user: "{{ item.u }}"
        rights: "{{ item.r }}"
        type: "{{ item.t }}"
        state: "{{ item.s }}"
        inherit: 'ContainerInherit, ObjectInherit'
        propagation: 'None'
      with_items:
        - { p: "{{ win_osquery_secret_path }}", u: 'Users', r: 'read,write', t: allow, s: absent }
        - { p: "{{ win_osquery_secret_path }}", u: 'Administrators', r: 'read,write', t: allow, s: present }

- name: Push central server certificate
  when: win_osquery_cert_push
  block:
    - name: Copy Fleet server certificate
      ansible.windows.win_copy:
        src: "{{ win_osquery_cert_orchestrator_path }}"
        dest: "{{ win_osquery_cert_path }}"

- name: Configure osqueryd
  ansible.windows.win_template:
    src: "{{ win_osquery_template }}"
    dest: "{{ win_osquery_dir }}\\osquery.conf"
  register: conf2
  notify:
    - Restart osqueryd
    - Restart osqueryd - script

- name: Configure osqueryd flags
  ansible.windows.win_template:
    src: "{{ win_osquery_flags_template }}"
    dest: "{{ win_osquery_dir }}\\osquery.flags"
  register: conf3
  notify:
    - Restart osqueryd
    - Restart osqueryd - script

- name: Update osqueryd.exe path
  ansible.windows.win_template:
    src: manage-osqueryd.ps1.j2
    dest: "{{ win_osquery_dir }}\\manage-osqueryd.ps1"
    backup: yes

- name: Remove permissions inheritance on osquery directories
  ansible.windows.win_acl_inheritance:
    path: "{{ win_osquery_dir }}"
    reorganize: yes
    state: absent

- name: Restrict permissions for Users on osquery directories
  ansible.windows.win_acl:
    path: "{{ item.p }}"
    user: "{{ item.u }}"
    rights: "{{ item.r }}"
    type: "{{ item.t }}"
    state: "{{ item.s }}"
    inherit: 'ContainerInherit, ObjectInherit'
    propagation: 'None'
  with_items:
    - { p: "{{ win_osquery_dir }}", u: 'Users', r: write, t: allow, s: absent }
    - { p: "{{ win_osquery_dir }}\\certs", u: 'Users', r: write, t: allow, s: absent }
    - { p: "{{ win_osquery_dir }}\\log", u: 'Users', r: 'read,write', t: allow, s: absent }
    - { p: "{{ win_osquery_dir }}\\packs", u: 'Users', r: write, t: allow, s: absent }

# https://github.com/facebook/osquery/pull/3887
# https://osquery.readthedocs.io/en/stable/installation/install-windows/#enabling-windows-event-log-support
- name: Check if osquery windows event log installed
  ansible.windows.win_stat:
    path: "{{ win_osquery_dir }}\\osquery_man_installed"
  register: osquerymaninstalled
- name: Win Event logger should be enabled
  when:
    - not osquerymaninstalled.stat.exists
    - "'windows_event_log' in win_osquery_logger_plugin"
  block:
    - name: Fixme! missing file in msi
      ansible.windows.win_copy:
        src: osquery.man
        dest: "{{ win_osquery_dir }}\\osquery.man"
      when: win_osquery_url|string

    - name: Enable Windows Event Log support
      ansible.windows.win_command: "wevtutil im \"{{ win_osquery_dir }}\\osquery.man\""
      notify:
        - Restart osqueryd
        - Restart osqueryd - script

    # - name: Check WINEVT osquery channel configuration
    #   ansible.windows.win_command: "wevtutil gl \"osquery\""
    #   changed_when: false
    #   register: evtosquery

    # FIXME! not working
    - name: WINEVT osquery Channel Event Log size review
      ansible.windows.win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\osquery"
        value: MaxSize
        datatype: dword
        data: "{{ win_eventlog_maxsize }}"
        # when: "'maxsize: {{ win_eventlog_maxsize }}' not in evtosquery.stdout"

    - name: WINEVT Channels Event Log retention review
      ansible.windows.win_regedit:
        key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\osquery"
        value: Retention
        datatype: dword
        data: "{{ win_eventlog_retention }}"
        # when: "'retention: false' not in evtosquery.stdout"

    # - name: Check WINEVT osquery channel configuration
    #   ansible.windows.win_command: "wevtutil gl \"osquery\""
    #   changed_when: false

    # - name: WINEVT osquery channel configuration - wevtutil
    #   ansible.windows.win_command: "wevtutil sl \"osquery\" /ms:{{ win_eventlog_maxsize }} /rt:false /ab:false"
    #   when: "'maxsize: {{ win_eventlog_maxsize }}' not in evtosquery.stdout"

    # - name: Check WINEVT osquery channel configuration
    #   ansible.windows.win_command: "wevtutil gl \"osquery\""
    #   changed_when: false

    - name: Add task marker
      ansible.windows.win_file:
        path: "{{ win_osquery_dir }}\\osquery_man_installed"
        state: touch
- name: Check if osquery windows event log status disabled
  ansible.windows.win_stat:
    path: "{{ win_osquery_dir }}\\osquery_man_uninstalled"
  register: osquerymanimported
- name: Win Event logger should not be enabled
  when:
    - not osquerymaninstalled.stat.exists
    - "'windows_event_log' not in win_osquery_logger_plugin"
  block:
    - name: Disable Windows Event Log support
      ansible.windows.win_command: "wevtutil um \"{{ win_osquery_dir }}\\osquery.man\""
      notify:
        - Restart osqueryd
        - Restart osqueryd - script
    - name: Add task marker
      ansible.windows.win_file:
        path: "{{ win_osquery_dir }}\\osquery_man_uninstalled"
        state: touch

- name: Osquery service enabled
  when: win_osqueryd_service_enable|bool and (conf1.changed or conf2.changed or conf3.changed)
  block:
    # https://github.com/ansible/ansible/issues/35661
    - name: Validate osqueryd config
      ansible.windows.win_command: >
        "{{ win_osquery_dir }}\\osqueryi.exe" --config_path "{{ win_osquery_dir }}\\osquery.conf" \
            --config_check --verbose
      changed_when: false
    - name: Install and start osqueryd service
      # win_shell: "%ProgramData%\\osquery\\manage-osqueryd.ps1 -install -start"
      ansible.windows.win_shell: "{{ item }}"
      with_items:
        # - "PowerShell.exe -ExecutionPolicy Bypass -File c:\\ProgramData\\osquery\\manage-osqueryd.ps1 -install"
        - "PowerShell.exe -ExecutionPolicy Bypass -File \"{{ win_osquery_dir }}\\manage-osqueryd.ps1\" -install
            -args '--flagfile \"{{ win_osquery_dir | regex_replace('^c:', '') }}\\osquery.flags\"'"
        - "PowerShell.exe -ExecutionPolicy Bypass -File \"{{ win_osquery_dir }}\\manage-osqueryd.ps1\" -start"
      failed_when: false
- name: Osquery service disabled
  when: not win_osqueryd_service_enable|bool
  block:
    - name: Uninstall and stop osqueryd service
      ansible.windows.win_shell: "{{ item }}"
      with_items:
        - "PowerShell.exe -ExecutionPolicy Bypass -File \"{{ win_osquery_dir }}\\manage-osqueryd.ps1\" -uninstall"
        - "PowerShell.exe -ExecutionPolicy Bypass -File \"{{ win_osquery_dir }}\\manage-osqueryd.ps1\" -stop"
      failed_when: false

- name: Wait for osquery.db path to exist after first start
  ansible.builtin.pause:
    seconds: 5

- name: Restrict permissions for Users on osquery directories - post first start
  ansible.windows.win_acl:
    path: "{{ item.p }}"
    user: "{{ item.u }}"
    rights: "{{ item.r }}"
    type: "{{ item.t }}"
    state: "{{ item.s }}"
    inherit: 'None'
    propagation: 'InheritOnly'
  with_items:
    - { p: "{{ win_osquerydb_dir }}", u: 'Users', r: write, t: allow, s: absent }
